[package]
name = "static-bench"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "tachyon"
path = "src/tachyon.rs"

[[bin]]
name = "axum"
path = "src/axum.rs"

[[bin]]
name = "actix"
path = "src/actix.rs"

[[bin]]
name = "rocket"
path = "src/rocket.rs"

[[bin]]
name = "salvo"
path = "src/salvo.rs"

[dependencies]
tachyon-web = { path = "../.." }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "net", "fs"] }
axum = { workspace = true }
tower-http = { workspace = true, features = ["fs", "set-header"] }
actix-web = { workspace = true }
actix-files = { workspace = true }
rocket = { workspace = true }
salvo = { workspace = true, features = ["rustls", "serve-static"] }
