[package]
name = "api-bench"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "tachyon"
path = "src/tachyon.rs"

[[bin]]
name = "axum"
path = "src/axum.rs"

[[bin]]
name = "actix"
path = "src/actix.rs"

[[bin]]
name = "rocket"
path = "src/rocket.rs"

[[bin]]
name = "salvo"
path = "src/salvo.rs"

[dependencies]
tachyon-web = { path = "../.." }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "net"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
axum = { workspace = true }
actix-web = { workspace = true }
rocket = { workspace = true, features = ["json"] }
salvo = { workspace = true, features = ["rustls"] }
